select * from ageDB;
insert into ageDB values(1, '1살');
insert into ageDB values(2, '2살');
insert into ageDB values(3, '3살');
insert into ageDB values(4, '4살');
insert into ageDB values(5, '5살');
insert into ageDB values(6, '6살');
insert into ageDB values(7, '7살');
insert into ageDB values(8, '8살');
insert into ageDB values(9, '9살');
insert into ageDB values(10, '10살');
insert into ageDB values(11, '11살');
insert into ageDB values(12, '12살');
insert into ageDB values(13, '13살');
insert into ageDB values(14, '14살');
insert into ageDB values(15, '15살');
insert into ageDB values(16, '16살');
insert into ageDB values(17, '17살');
insert into ageDB values(18, '18살');
insert into ageDB values(19, '19살');
insert into ageDB values(20, '20살');
insert into ageDB values(21, '21살');
insert into ageDB values(22, '22살');
insert into ageDB values(23, '23살');
insert into ageDB values(24, '24살');
insert into ageDB values(25, '25살');
insert into ageDB values(26, '26살');
insert into ageDB values(27, '27살');
insert into ageDB values(28, '28살');
insert into ageDB values(29, '29살');
insert into ageDB values(30, '30살');
insert into ageDB values(31, '31살');
insert into ageDB values(32, '32살');
insert into ageDB values(33, '33살');
insert into ageDB values(34, '34살');
insert into ageDB values(35, '35살');
insert into ageDB values(36, '36살');
insert into ageDB values(37, '37살');
insert into ageDB values(38, '38살');
insert into ageDB values(39, '39살');
insert into ageDB values(40, '40살');
insert into ageDB values(41, '41살');
insert into ageDB values(42, '42살');
insert into ageDB values(43, '43살');
insert into ageDB values(44, '44살');
insert into ageDB values(45, '45살');
insert into ageDB values(46, '46살');
insert into ageDB values(47, '47살');
insert into ageDB values(48, '48살');
insert into ageDB values(49, '49살');
insert into ageDB values(50, '50살');
insert into ageDB values(51, '51살');
insert into ageDB values(52, '52살');
insert into ageDB values(53, '53살');
insert into ageDB values(54, '54살');
insert into ageDB values(55, '55살');
insert into ageDB values(56, '56살');
insert into ageDB values(57, '57살');
insert into ageDB values(58, '58살');
insert into ageDB values(59, '59살');
insert into ageDB values(60, '60살');
insert into ageDB values(61, '61살');
insert into ageDB values(62, '62살');
insert into ageDB values(63, '63살');
insert into ageDB values(64, '64살');
insert into ageDB values(65, '65살');
insert into ageDB values(66, '66살');
insert into ageDB values(67, '67살');
insert into ageDB values(68, '68살');
insert into ageDB values(69, '69살');
insert into ageDB values(70, '70살');
insert into ageDB values(71, '71살');
insert into ageDB values(72, '72살');
insert into ageDB values(73, '73살');
insert into ageDB values(74, '74살');
insert into ageDB values(75, '75살');
insert into ageDB values(76, '76살');
insert into ageDB values(77, '77살');
insert into ageDB values(78, '78살');
insert into ageDB values(79, '79살');
insert into ageDB values(80, '80살');
insert into ageDB values(81, '81살');
insert into ageDB values(82, '82살');
insert into ageDB values(83, '83살');
insert into ageDB values(84, '84살');
insert into ageDB values(85, '85살');
insert into ageDB values(86, '86살');
insert into ageDB values(87, '87살');
insert into ageDB values(88, '88살');
insert into ageDB values(89, '89살');
insert into ageDB values(90, '90살');
insert into ageDB values(91, '91살');
insert into ageDB values(92, '92살');
insert into ageDB values(93, '93살');
insert into ageDB values(94, '94살');
insert into ageDB values(95, '95살');
insert into ageDB values(96, '96살');
insert into ageDB values(97, '97살');
insert into ageDB values(98, '98살');
insert into ageDB values(99, '99살');
insert into ageDB values(100, '100살');
commit;

select * from petDB;
insert into petDB values(1, '개');
insert into petDB values(2, '고양이');
insert into petDB values(3, '새');
insert into petDB values(4, '토끼');
insert into petDB values(5, '햄스터');
insert into petDB values(6, '물고기');
insert into petDB values(7, '거북이');
insert into petDB values(8, '기타');
insert into petDB values(9, '키우고 싶은/좋아하는 동물 없음');
commit;

select * from lastNameDB;
insert into lastNameDB values(1, '김');
insert into lastNameDB values(2, '이');
insert into lastNameDB values(3, '박');
insert into lastNameDB values(4, '최');
insert into lastNameDB values(5, '정');
insert into lastNameDB values(6, '강');
insert into lastNameDB values(7, '조');
insert into lastNameDB values(8, '윤');
insert into lastNameDB values(9, '장');
insert into lastNameDB values(10, '임');
insert into lastNameDB values(11, '오');
insert into lastNameDB values(12, '한');
insert into lastNameDB values(13, '신');
insert into lastNameDB values(14, '추');
insert into lastNameDB values(15, '권');
insert into lastNameDB values(16, '황');
insert into lastNameDB values(17, '안');
insert into lastNameDB values(18, '송');
insert into lastNameDB values(19, '유');
insert into lastNameDB values(20, '홍');
insert into lastNameDB values(21, '기타');
commit;

select * from transferDB;
insert into transferDB values(1, '확실하다 난 날아오를테다');
insert into transferDB values(2, '다음 생을 기약한다');
insert into transferDB values(3, '왜 묻는지 모르겠다');
commit;

select * from digitalDB;
insert into digitalDB values(1, '의존도가 높은 편이다');
insert into digitalDB values(2, '중복될 것 같은 느낌이 든다');
insert into digitalDB values(3, '디지털 기기가 없으면 불안하다');
insert into digitalDB values(4, '없으면 살 수가 없다');
commit;

select * from happyDB;
insert into happyDB values(1, '아주 행복하다');
insert into happyDB values(2, '대체로 행복하다');
insert into happyDB values(3, '보통이다');
insert into happyDB values(4, '대체로 불행하다');
insert into happyDB values(5, '아주 불행하다');
COMMIT;

create table tourDB (
  tourDB_id1 varchar2(100),
  tourDB_id2 varchar2(100)
);
select * from tourDB;
insert into tourDB values('아시아', '대한민국');
insert into tourDB values('아시아', '태국');
insert into tourDB values('아시아', '베트남');
insert into tourDB values('아시아', '일본');
insert into tourDB values('아시아', '라오스');
insert into tourDB values('아메리카', '브라질');
insert into tourDB values('아메리카', '미국');
insert into tourDB values('아메리카', '캐나다');
insert into tourDB values('아메리카', '멕시코');
insert into tourDB values('아메리카', '쿠바');
insert into tourDB values('아프리카', '남아프리카공화국');
insert into tourDB values('아프리카', '이집트');
insert into tourDB values('아프리카', '모로코');
insert into tourDB values('아프리카', '가나');
insert into tourDB values('아프리카', '콩고');
insert into tourDB values('오세아니아', '오스트레일리아');
insert into tourDB values('오세아니아', '뉴질랜드');
insert into tourDB values('오세아니아', '피지');
insert into tourDB values('오세아니아', '파푸아뉴기니');
insert into tourDB values('오세아니아', '솔로몬제도');
commit;

select * from oldDB;
insert into oldDB values(1, '늦게까지 노는게 피곤하고 다음날 걱정될 때');
insert into oldDB values(2, '교복입은 학생들이 예뻐보일 때');
insert into oldDB values(3, '주변 사람들이 하나 둘 결혼할 때');
insert into oldDB values(4, '새롭게 도전하는것이 망설여질 때');
insert into oldDB values(5, '군인을 아저씨라고 부르기 민망할 때');
insert into oldDB values(6, '건강식품, 건강 프로그램 찾게 될 때');
insert into oldDB values(7, '요즘 개그가 이해가 안될 때');
insert into oldDB values(8, '낯선 사람이랑 얘기하는게 어색하지 않을 때');
insert into oldDB values(9, '물건값을 깎는 것에 집착할 때');
commit;

select * from mobileDB;
insert into mobileDB values(1, '유튜브');
insert into mobileDB values(2, '페이스북');
insert into mobileDB values(3, '트위터');
insert into mobileDB values(4, '카카오톡');
insert into mobileDB values(5, '인스타그램');
commit;